// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateIdentityData, CreateIdentityErrors, CreateIdentityResponses, CreateTokenData, CreateTokenErrors, CreateTokenResponses, DeleteRepositoryData, DeleteRepositoryErrors, DeleteRepositoryManifestData, DeleteRepositoryManifestErrors, DeleteRepositoryManifestResponses, DeleteRepositoryResponses, DeleteRepositoryTagData, DeleteRepositoryTagErrors, DeleteRepositoryTagResponses, GetMeData, GetMeErrors, GetMeResponses, GetPrincipalData, GetPrincipalErrors, GetPrincipalResponses, GetRepositoryData, GetRepositoryErrors, GetRepositoryResponses, GetSystemData, GetSystemResponses, GrantPermissionData, GrantPermissionErrors, GrantPermissionResponses, ListAuditActionsData, ListAuditActionsResponses, ListAuditEventsData, ListAuditEventsErrors, ListAuditEventsResponses, ListPrincipalsData, ListPrincipalsErrors, ListPrincipalsResponses, ListRepositoriesData, ListRepositoriesErrors, ListRepositoriesResponses, ListRepositoryPermissionsData, ListRepositoryPermissionsErrors, ListRepositoryPermissionsResponses, ListTokensData, ListTokensErrors, ListTokensResponses, ListUploadsData, ListUploadsResponses, RevokePermissionData, RevokePermissionErrors, RevokePermissionResponses, RevokeTokenData, RevokeTokenErrors, RevokeTokenResponses, RunGcData, RunGcErrors, RunGcResponses, UpdatePrincipalData, UpdatePrincipalErrors, UpdatePrincipalResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Audit events, newest first, with filters and cursor pagination.
 */
export const listAuditEvents = <ThrowOnError extends boolean = false>(options?: Options<ListAuditEventsData, ThrowOnError>): RequestResult<ListAuditEventsResponses, ListAuditEventsErrors, ThrowOnError> => (options?.client ?? client).get<ListAuditEventsResponses, ListAuditEventsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/audit',
    ...options
});

/**
 * Every action name the audit log can contain.
 */
export const listAuditActions = <ThrowOnError extends boolean = false>(options?: Options<ListAuditActionsData, ThrowOnError>): RequestResult<ListAuditActionsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListAuditActionsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/audit/actions',
    ...options
});

/**
 * Runs garbage collection now (use `dry_run` first).
 */
export const runGc = <ThrowOnError extends boolean = false>(options: Options<RunGcData, ThrowOnError>): RequestResult<RunGcResponses, RunGcErrors, ThrowOnError> => (options.client ?? client).post<RunGcResponses, RunGcErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/gc',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * The signed-in admin.
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>): RequestResult<GetMeResponses, GetMeErrors, ThrowOnError> => (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/me',
    ...options
});

/**
 * GitHub admins (from configuration) and all principals.
 */
export const listPrincipals = <ThrowOnError extends boolean = false>(options?: Options<ListPrincipalsData, ThrowOnError>): RequestResult<ListPrincipalsResponses, ListPrincipalsErrors, ThrowOnError> => (options?.client ?? client).get<ListPrincipalsResponses, ListPrincipalsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/principals',
    ...options
});

/**
 * Creates a token-only identity (no web login).
 */
export const createIdentity = <ThrowOnError extends boolean = false>(options: Options<CreateIdentityData, ThrowOnError>): RequestResult<CreateIdentityResponses, CreateIdentityErrors, ThrowOnError> => (options.client ?? client).post<CreateIdentityResponses, CreateIdentityErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/principals',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * A principal with its tokens and repository grants.
 */
export const getPrincipal = <ThrowOnError extends boolean = false>(options: Options<GetPrincipalData, ThrowOnError>): RequestResult<GetPrincipalResponses, GetPrincipalErrors, ThrowOnError> => (options.client ?? client).get<GetPrincipalResponses, GetPrincipalErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/principals/{id}',
    ...options
});

/**
 * Enables/disables an identity or renames its display name.
 */
export const updatePrincipal = <ThrowOnError extends boolean = false>(options: Options<UpdatePrincipalData, ThrowOnError>): RequestResult<UpdatePrincipalResponses, UpdatePrincipalErrors, ThrowOnError> => (options.client ?? client).patch<UpdatePrincipalResponses, UpdatePrincipalErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/principals/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Tokens of a principal (secrets are never returned).
 */
export const listTokens = <ThrowOnError extends boolean = false>(options: Options<ListTokensData, ThrowOnError>): RequestResult<ListTokensResponses, ListTokensErrors, ThrowOnError> => (options.client ?? client).get<ListTokensResponses, ListTokensErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/principals/{id}/tokens',
    ...options
});

/**
 * Issues a token. The secret is returned once. Admins may mint tokens for
 * identities and for their own GitHub principal only.
 */
export const createToken = <ThrowOnError extends boolean = false>(options: Options<CreateTokenData, ThrowOnError>): RequestResult<CreateTokenResponses, CreateTokenErrors, ThrowOnError> => (options.client ?? client).post<CreateTokenResponses, CreateTokenErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/principals/{id}/tokens',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revokes a token immediately.
 */
export const revokeToken = <ThrowOnError extends boolean = false>(options: Options<RevokeTokenData, ThrowOnError>): RequestResult<RevokeTokenResponses, RevokeTokenErrors, ThrowOnError> => (options.client ?? client).delete<RevokeTokenResponses, RevokeTokenErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/principals/{id}/tokens/{token_id}',
    ...options
});

/**
 * Repositories, alphabetically, with a substring filter.
 */
export const listRepositories = <ThrowOnError extends boolean = false>(options?: Options<ListRepositoriesData, ThrowOnError>): RequestResult<ListRepositoriesResponses, ListRepositoriesErrors, ThrowOnError> => (options?.client ?? client).get<ListRepositoriesResponses, ListRepositoriesErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/repositories',
    ...options
});

/**
 * Deletes a repository: tags, manifests, grants and uploads go; blobs are
 * reclaimed by the next garbage collection.
 */
export const deleteRepository = <ThrowOnError extends boolean = false>(options: Options<DeleteRepositoryData, ThrowOnError>): RequestResult<DeleteRepositoryResponses, DeleteRepositoryErrors, ThrowOnError> => (options.client ?? client).delete<DeleteRepositoryResponses, DeleteRepositoryErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/repositories/{id}',
    ...options
});

/**
 * A repository with its tags and manifests (including referrers).
 */
export const getRepository = <ThrowOnError extends boolean = false>(options: Options<GetRepositoryData, ThrowOnError>): RequestResult<GetRepositoryResponses, GetRepositoryErrors, ThrowOnError> => (options.client ?? client).get<GetRepositoryResponses, GetRepositoryErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/repositories/{id}',
    ...options
});

/**
 * Deletes a manifest and every tag pointing at it.
 */
export const deleteRepositoryManifest = <ThrowOnError extends boolean = false>(options: Options<DeleteRepositoryManifestData, ThrowOnError>): RequestResult<DeleteRepositoryManifestResponses, DeleteRepositoryManifestErrors, ThrowOnError> => (options.client ?? client).delete<DeleteRepositoryManifestResponses, DeleteRepositoryManifestErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/repositories/{id}/manifests/{digest}',
    ...options
});

/**
 * Who may access a repository.
 */
export const listRepositoryPermissions = <ThrowOnError extends boolean = false>(options: Options<ListRepositoryPermissionsData, ThrowOnError>): RequestResult<ListRepositoryPermissionsResponses, ListRepositoryPermissionsErrors, ThrowOnError> => (options.client ?? client).get<ListRepositoryPermissionsResponses, ListRepositoryPermissionsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/repositories/{id}/permissions',
    ...options
});

/**
 * Removes a principal's grant on a repository.
 */
export const revokePermission = <ThrowOnError extends boolean = false>(options: Options<RevokePermissionData, ThrowOnError>): RequestResult<RevokePermissionResponses, RevokePermissionErrors, ThrowOnError> => (options.client ?? client).delete<RevokePermissionResponses, RevokePermissionErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/repositories/{id}/permissions/{principal_id}',
    ...options
});

/**
 * Grants (or changes) a principal's level on a repository.
 */
export const grantPermission = <ThrowOnError extends boolean = false>(options: Options<GrantPermissionData, ThrowOnError>): RequestResult<GrantPermissionResponses, GrantPermissionErrors, ThrowOnError> => (options.client ?? client).put<GrantPermissionResponses, GrantPermissionErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/repositories/{id}/permissions/{principal_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Removes a tag (the manifest stays).
 */
export const deleteRepositoryTag = <ThrowOnError extends boolean = false>(options: Options<DeleteRepositoryTagData, ThrowOnError>): RequestResult<DeleteRepositoryTagResponses, DeleteRepositoryTagErrors, ThrowOnError> => (options.client ?? client).delete<DeleteRepositoryTagResponses, DeleteRepositoryTagErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/repositories/{id}/tags/{tag}',
    ...options
});

/**
 * Storage backend, database size and registry totals.
 */
export const getSystem = <ThrowOnError extends boolean = false>(options?: Options<GetSystemData, ThrowOnError>): RequestResult<GetSystemResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetSystemResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/system',
    ...options
});

/**
 * Upload sessions in flight.
 */
export const listUploads = <ThrowOnError extends boolean = false>(options?: Options<ListUploadsData, ThrowOnError>): RequestResult<ListUploadsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListUploadsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'minregistry_session',
            type: 'apiKey'
        }],
    url: '/api/v1/uploads',
    ...options
});
