// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AuditActionsResponse = {
    actions: Array<string>;
};

export type AuditEventSummary = {
    id: string;
    ts: string;
    principal_id?: string | null;
    principal_name?: string | null;
    action: string;
    repository?: string | null;
    reference?: string | null;
    digest?: string | null;
    client_ip?: string | null;
    user_agent?: string | null;
    outcome: AuditOutcome;
    detail: {
        [key: string]: unknown;
    };
};

export type AuditListResponse = {
    /**
     * Newest first.
     */
    items: Array<AuditEventSummary>;
    /**
     * Pass as `cursor` to get the next (older) page; absent on the last page.
     */
    next_cursor?: string | null;
};

export type AuditOutcome = 'ok' | 'denied' | 'error';

export type CreateIdentityRequest = {
    /**
     * Lower-case letters, digits, `.`, `_`, `-`; used as the `docker login` username.
     */
    name: string;
    display_name?: string | null;
};

export type CreateTokenRequest = {
    name: string;
    /**
     * Optional RFC 3339 expiry; tokens never expire by default.
     */
    expires_at?: string | null;
};

export type CreateTokenResponse = {
    token: TokenSummary;
    /**
     * The secret. Shown only in this response; it cannot be retrieved later.
     */
    secret: string;
    /**
     * Username to pair with the secret (`docker login -u`).
     */
    username: string;
};

export type DatabaseSummary = {
    path: string;
    size_bytes: number;
};

export type ErrorDetail = {
    /**
     * Machine-readable code, e.g. `not_found`, `unauthenticated`, `csrf`.
     */
    code: string;
    message: string;
};

export type ErrorResponse = {
    error: ErrorDetail;
};

export type GcRequest = {
    /**
     * Report what would be deleted without deleting anything.
     */
    dry_run?: boolean;
    /**
     * Also delete manifests that no tag reaches (directly, via an index or as a referrer).
     */
    delete_untagged?: boolean;
    /**
     * Keep content younger than this (default `MINREGISTRY_GC_MIN_AGE`).
     */
    min_age_seconds?: number | null;
};

export type GcResponse = {
    dry_run: boolean;
    delete_untagged: boolean;
    min_age_seconds: number;
    manifests_deleted: number;
    blobs_deleted: number;
    bytes_freed: number;
    orphans_deleted: number;
    blobs_kept_young: number;
    errors: number;
    duration_ms: number;
};

export type GrantPermissionRequest = {
    level: PermissionLevel;
};

export type ManifestSummary = {
    digest: string;
    media_type: string;
    size: number;
    artifact_type?: string | null;
    /**
     * Set for referrers (signatures, SBOMs, …): the manifest they refer to.
     */
    subject_digest?: string | null;
    platforms: Array<PlatformSummary>;
    annotations: {
        [key: string]: string;
    };
    tags: Array<string>;
    created_at: string;
    pushed_by?: string | null;
};

export type MeResponse = {
    principal: PrincipalSummary;
};

export type PermissionLevel = 'read' | 'write' | 'owner';

export type PlatformSummary = {
    os: string;
    architecture: string;
    variant?: string | null;
};

export type PrincipalDetail = {
    principal: PrincipalSummary;
    tokens: Array<TokenSummary>;
    permissions: Array<PrincipalPermissionSummary>;
};

export type PrincipalKind = 'github' | 'identity';

export type PrincipalListResponse = {
    /**
     * GitHub logins allowed to sign in (from configuration, read-only).
     */
    admin_logins: Array<string>;
    principals: Array<PrincipalSummary>;
};

export type PrincipalPermissionSummary = {
    repository: RepositoryRefSummary;
    level: PermissionLevel;
    granted_by?: string | null;
    granted_at: string;
};

export type PrincipalRefSummary = {
    id: string;
    kind: PrincipalKind;
    name: string;
};

export type PrincipalSummary = {
    id: string;
    kind: PrincipalKind;
    name: string;
    display_name: string;
    enabled: boolean;
    /**
     * GitHub principal currently listed in `MINREGISTRY_ADMIN_GITHUB_LOGINS`.
     */
    is_admin: boolean;
    /**
     * Whether the principal can authenticate right now.
     */
    active: boolean;
    active_token_count: number;
    created_at: string;
};

export type RepositoryDetail = {
    id: string;
    name: string;
    created_at: string;
    created_by?: string | null;
    tags: Array<TagSummary>;
    manifests: Array<ManifestSummary>;
};

export type RepositoryListResponse = {
    items: Array<RepositorySummary>;
    total: number;
};

export type RepositoryPermissionSummary = {
    principal: PrincipalRefSummary;
    level: PermissionLevel;
    granted_by?: string | null;
    granted_at: string;
};

export type RepositoryRefSummary = {
    id: string;
    name: string;
};

export type RepositorySummary = {
    id: string;
    name: string;
    created_at: string;
    created_by?: string | null;
    tag_count: number;
    manifest_count: number;
    last_push_at?: string | null;
};

export type StorageSummary = {
    /**
     * `fs` or `s3`.
     */
    backend: string;
    location: string;
};

export type SystemResponse = {
    version: string;
    started_at: string;
    storage: StorageSummary;
    database: DatabaseSummary;
    upload_dir: string;
    upload_ttl_seconds: number;
    uploads_in_flight: number;
    repository_count: number;
    manifest_count: number;
    blob_count: number;
    blob_bytes: number;
    gc_cron?: string | null;
    gc_min_age_seconds: number;
    audit_retention_days: number;
    audit_blob_reads: boolean;
};

export type TagSummary = {
    name: string;
    digest: string;
    updated_at: string;
    updated_by?: string | null;
};

export type TokenStatus = 'active' | 'expired' | 'revoked';

export type TokenSummary = {
    id: string;
    name: string;
    /**
     * First characters of the secret, to recognize it.
     */
    prefix: string;
    status: TokenStatus;
    created_at: string;
    created_by?: string | null;
    expires_at?: string | null;
    revoked_at?: string | null;
    last_used_at?: string | null;
};

export type UpdatePrincipalRequest = {
    enabled?: boolean | null;
    display_name?: string | null;
};

export type UploadSummary = {
    uuid: string;
    repository: string;
    principal: string;
    /**
     * Bytes received so far.
     */
    offset: number;
    started_at: string;
    last_activity_at: string;
};

export type ListAuditEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Exact principal name.
         */
        principal?: string;
        /**
         * Exact repository name.
         */
        repository?: string;
        /**
         * Exact action, e.g. `manifest.push`.
         */
        action?: string;
        outcome?: AuditOutcome;
        /**
         * Inclusive lower bound (RFC 3339).
         */
        from?: string;
        /**
         * Exclusive upper bound (RFC 3339).
         */
        to?: string;
        /**
         * `next_cursor` of the previous page.
         */
        cursor?: string;
        /**
         * Page size (default 50, max 500).
         */
        limit?: number;
    };
    url: '/api/v1/audit';
};

export type ListAuditEventsErrors = {
    400: ErrorResponse;
};

export type ListAuditEventsError = ListAuditEventsErrors[keyof ListAuditEventsErrors];

export type ListAuditEventsResponses = {
    200: AuditListResponse;
};

export type ListAuditEventsResponse = ListAuditEventsResponses[keyof ListAuditEventsResponses];

export type ListAuditActionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/audit/actions';
};

export type ListAuditActionsResponses = {
    200: AuditActionsResponse;
};

export type ListAuditActionsResponse = ListAuditActionsResponses[keyof ListAuditActionsResponses];

export type RunGcData = {
    body: GcRequest;
    path?: never;
    query?: never;
    url: '/api/v1/gc';
};

export type RunGcErrors = {
    400: ErrorResponse;
};

export type RunGcError = RunGcErrors[keyof RunGcErrors];

export type RunGcResponses = {
    200: GcResponse;
};

export type RunGcResponse = RunGcResponses[keyof RunGcResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type GetMeErrors = {
    /**
     * Not signed in
     */
    401: ErrorResponse;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    200: MeResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type ListPrincipalsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/principals';
};

export type ListPrincipalsErrors = {
    401: ErrorResponse;
};

export type ListPrincipalsError = ListPrincipalsErrors[keyof ListPrincipalsErrors];

export type ListPrincipalsResponses = {
    200: PrincipalListResponse;
};

export type ListPrincipalsResponse = ListPrincipalsResponses[keyof ListPrincipalsResponses];

export type CreateIdentityData = {
    body: CreateIdentityRequest;
    path?: never;
    query?: never;
    url: '/api/v1/principals';
};

export type CreateIdentityErrors = {
    400: ErrorResponse;
    /**
     * Name already taken
     */
    409: ErrorResponse;
};

export type CreateIdentityError = CreateIdentityErrors[keyof CreateIdentityErrors];

export type CreateIdentityResponses = {
    201: PrincipalSummary;
};

export type CreateIdentityResponse = CreateIdentityResponses[keyof CreateIdentityResponses];

export type GetPrincipalData = {
    body?: never;
    path: {
        /**
         * Principal id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/principals/{id}';
};

export type GetPrincipalErrors = {
    404: ErrorResponse;
};

export type GetPrincipalError = GetPrincipalErrors[keyof GetPrincipalErrors];

export type GetPrincipalResponses = {
    200: PrincipalDetail;
};

export type GetPrincipalResponse = GetPrincipalResponses[keyof GetPrincipalResponses];

export type UpdatePrincipalData = {
    body: UpdatePrincipalRequest;
    path: {
        /**
         * Principal id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/principals/{id}';
};

export type UpdatePrincipalErrors = {
    /**
     * GitHub admins are managed through configuration
     */
    400: ErrorResponse;
    404: ErrorResponse;
};

export type UpdatePrincipalError = UpdatePrincipalErrors[keyof UpdatePrincipalErrors];

export type UpdatePrincipalResponses = {
    200: PrincipalSummary;
};

export type UpdatePrincipalResponse = UpdatePrincipalResponses[keyof UpdatePrincipalResponses];

export type ListTokensData = {
    body?: never;
    path: {
        /**
         * Principal id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/principals/{id}/tokens';
};

export type ListTokensErrors = {
    404: ErrorResponse;
};

export type ListTokensError = ListTokensErrors[keyof ListTokensErrors];

export type ListTokensResponses = {
    200: Array<TokenSummary>;
};

export type ListTokensResponse = ListTokensResponses[keyof ListTokensResponses];

export type CreateTokenData = {
    body: CreateTokenRequest;
    path: {
        /**
         * Principal id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/principals/{id}/tokens';
};

export type CreateTokenErrors = {
    400: ErrorResponse;
    /**
     * Another admin's GitHub principal
     */
    403: ErrorResponse;
    404: ErrorResponse;
};

export type CreateTokenError = CreateTokenErrors[keyof CreateTokenErrors];

export type CreateTokenResponses = {
    201: CreateTokenResponse;
};

export type CreateTokenResponse2 = CreateTokenResponses[keyof CreateTokenResponses];

export type RevokeTokenData = {
    body?: never;
    path: {
        /**
         * Principal id
         */
        id: string;
        /**
         * Token id
         */
        token_id: string;
    };
    query?: never;
    url: '/api/v1/principals/{id}/tokens/{token_id}';
};

export type RevokeTokenErrors = {
    404: ErrorResponse;
};

export type RevokeTokenError = RevokeTokenErrors[keyof RevokeTokenErrors];

export type RevokeTokenResponses = {
    /**
     * Revoked
     */
    204: void;
};

export type RevokeTokenResponse = RevokeTokenResponses[keyof RevokeTokenResponses];

export type ListRepositoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Substring filter on the repository name.
         */
        q?: string;
        /**
         * Page size (default 50, max 500).
         */
        limit?: number;
        offset?: number;
    };
    url: '/api/v1/repositories';
};

export type ListRepositoriesErrors = {
    401: ErrorResponse;
};

export type ListRepositoriesError = ListRepositoriesErrors[keyof ListRepositoriesErrors];

export type ListRepositoriesResponses = {
    200: RepositoryListResponse;
};

export type ListRepositoriesResponse = ListRepositoriesResponses[keyof ListRepositoriesResponses];

export type DeleteRepositoryData = {
    body?: never;
    path: {
        /**
         * Repository id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{id}';
};

export type DeleteRepositoryErrors = {
    404: ErrorResponse;
};

export type DeleteRepositoryError = DeleteRepositoryErrors[keyof DeleteRepositoryErrors];

export type DeleteRepositoryResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteRepositoryResponse = DeleteRepositoryResponses[keyof DeleteRepositoryResponses];

export type GetRepositoryData = {
    body?: never;
    path: {
        /**
         * Repository id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{id}';
};

export type GetRepositoryErrors = {
    404: ErrorResponse;
};

export type GetRepositoryError = GetRepositoryErrors[keyof GetRepositoryErrors];

export type GetRepositoryResponses = {
    200: RepositoryDetail;
};

export type GetRepositoryResponse = GetRepositoryResponses[keyof GetRepositoryResponses];

export type DeleteRepositoryManifestData = {
    body?: never;
    path: {
        /**
         * Repository id
         */
        id: string;
        /**
         * Manifest digest
         */
        digest: string;
    };
    query?: never;
    url: '/api/v1/repositories/{id}/manifests/{digest}';
};

export type DeleteRepositoryManifestErrors = {
    404: ErrorResponse;
};

export type DeleteRepositoryManifestError = DeleteRepositoryManifestErrors[keyof DeleteRepositoryManifestErrors];

export type DeleteRepositoryManifestResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteRepositoryManifestResponse = DeleteRepositoryManifestResponses[keyof DeleteRepositoryManifestResponses];

export type ListRepositoryPermissionsData = {
    body?: never;
    path: {
        /**
         * Repository id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{id}/permissions';
};

export type ListRepositoryPermissionsErrors = {
    404: ErrorResponse;
};

export type ListRepositoryPermissionsError = ListRepositoryPermissionsErrors[keyof ListRepositoryPermissionsErrors];

export type ListRepositoryPermissionsResponses = {
    200: Array<RepositoryPermissionSummary>;
};

export type ListRepositoryPermissionsResponse = ListRepositoryPermissionsResponses[keyof ListRepositoryPermissionsResponses];

export type RevokePermissionData = {
    body?: never;
    path: {
        /**
         * Repository id
         */
        id: string;
        /**
         * Principal id
         */
        principal_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{id}/permissions/{principal_id}';
};

export type RevokePermissionErrors = {
    404: ErrorResponse;
};

export type RevokePermissionError = RevokePermissionErrors[keyof RevokePermissionErrors];

export type RevokePermissionResponses = {
    /**
     * Revoked
     */
    204: void;
};

export type RevokePermissionResponse = RevokePermissionResponses[keyof RevokePermissionResponses];

export type GrantPermissionData = {
    body: GrantPermissionRequest;
    path: {
        /**
         * Repository id
         */
        id: string;
        /**
         * Principal id
         */
        principal_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{id}/permissions/{principal_id}';
};

export type GrantPermissionErrors = {
    404: ErrorResponse;
};

export type GrantPermissionError = GrantPermissionErrors[keyof GrantPermissionErrors];

export type GrantPermissionResponses = {
    200: RepositoryPermissionSummary;
};

export type GrantPermissionResponse = GrantPermissionResponses[keyof GrantPermissionResponses];

export type DeleteRepositoryTagData = {
    body?: never;
    path: {
        /**
         * Repository id
         */
        id: string;
        /**
         * Tag name
         */
        tag: string;
    };
    query?: never;
    url: '/api/v1/repositories/{id}/tags/{tag}';
};

export type DeleteRepositoryTagErrors = {
    404: ErrorResponse;
};

export type DeleteRepositoryTagError = DeleteRepositoryTagErrors[keyof DeleteRepositoryTagErrors];

export type DeleteRepositoryTagResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteRepositoryTagResponse = DeleteRepositoryTagResponses[keyof DeleteRepositoryTagResponses];

export type GetSystemData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system';
};

export type GetSystemResponses = {
    200: SystemResponse;
};

export type GetSystemResponse = GetSystemResponses[keyof GetSystemResponses];

export type ListUploadsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/uploads';
};

export type ListUploadsResponses = {
    200: Array<UploadSummary>;
};

export type ListUploadsResponse = ListUploadsResponses[keyof ListUploadsResponses];
