// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createIdentity, createToken, deleteRepository, deleteRepositoryManifest, deleteRepositoryTag, getMe, getPrincipal, getRepository, getSystem, grantPermission, listAuditActions, listAuditEvents, listPrincipals, listRepositories, listRepositoryPermissions, listTokens, listUploads, type Options, revokePermission, revokeToken, runGc, updatePrincipal } from '../sdk.gen';
import type { CreateIdentityData, CreateIdentityError, CreateIdentityResponse, CreateTokenData, CreateTokenError, CreateTokenResponse2, DeleteRepositoryData, DeleteRepositoryError, DeleteRepositoryManifestData, DeleteRepositoryManifestError, DeleteRepositoryManifestResponse, DeleteRepositoryResponse, DeleteRepositoryTagData, DeleteRepositoryTagError, DeleteRepositoryTagResponse, GetMeData, GetMeError, GetMeResponse, GetPrincipalData, GetPrincipalError, GetPrincipalResponse, GetRepositoryData, GetRepositoryError, GetRepositoryResponse, GetSystemData, GetSystemResponse, GrantPermissionData, GrantPermissionError, GrantPermissionResponse, ListAuditActionsData, ListAuditActionsResponse, ListAuditEventsData, ListAuditEventsError, ListAuditEventsResponse, ListPrincipalsData, ListPrincipalsError, ListPrincipalsResponse, ListRepositoriesData, ListRepositoriesError, ListRepositoriesResponse, ListRepositoryPermissionsData, ListRepositoryPermissionsError, ListRepositoryPermissionsResponse, ListTokensData, ListTokensError, ListTokensResponse, ListUploadsData, ListUploadsResponse, RevokePermissionData, RevokePermissionError, RevokePermissionResponse, RevokeTokenData, RevokeTokenError, RevokeTokenResponse, RunGcData, RunGcError, RunGcResponse, UpdatePrincipalData, UpdatePrincipalError, UpdatePrincipalResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listAuditEventsQueryKey = (options?: Options<ListAuditEventsData>) => createQueryKey('listAuditEvents', options);

/**
 * Audit events, newest first, with filters and cursor pagination.
 */
export const listAuditEventsOptions = (options?: Options<ListAuditEventsData>) => queryOptions<ListAuditEventsResponse, ListAuditEventsError, ListAuditEventsResponse, ReturnType<typeof listAuditEventsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listAuditEvents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listAuditEventsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listAuditEventsInfiniteQueryKey = (options?: Options<ListAuditEventsData>): QueryKey<Options<ListAuditEventsData>> => createQueryKey('listAuditEvents', options, true);

/**
 * Audit events, newest first, with filters and cursor pagination.
 */
export const listAuditEventsInfiniteOptions = (options?: Options<ListAuditEventsData>) => {
    const opts = infiniteQueryOptions<ListAuditEventsResponse, ListAuditEventsError, InfiniteData<ListAuditEventsResponse>, QueryKey<Options<ListAuditEventsData>>, string | Pick<QueryKey<Options<ListAuditEventsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListAuditEventsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    cursor: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listAuditEvents({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listAuditEventsInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const listAuditActionsQueryKey = (options?: Options<ListAuditActionsData>) => createQueryKey('listAuditActions', options);

/**
 * Every action name the audit log can contain.
 */
export const listAuditActionsOptions = (options?: Options<ListAuditActionsData>) => queryOptions<ListAuditActionsResponse, DefaultError, ListAuditActionsResponse, ReturnType<typeof listAuditActionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listAuditActions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listAuditActionsQueryKey(options)
});

/**
 * Runs garbage collection now (use `dry_run` first).
 */
export const runGcMutation = (options?: Partial<Options<RunGcData>>): UseMutationOptions<RunGcResponse, RunGcError, Options<RunGcData>> => {
    const mutationOptions: UseMutationOptions<RunGcResponse, RunGcError, Options<RunGcData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await runGc({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getMeQueryKey = (options?: Options<GetMeData>) => createQueryKey('getMe', options);

/**
 * The signed-in admin.
 */
export const getMeOptions = (options?: Options<GetMeData>) => queryOptions<GetMeResponse, GetMeError, GetMeResponse, ReturnType<typeof getMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMeQueryKey(options)
});

export const listPrincipalsQueryKey = (options?: Options<ListPrincipalsData>) => createQueryKey('listPrincipals', options);

/**
 * GitHub admins (from configuration) and all principals.
 */
export const listPrincipalsOptions = (options?: Options<ListPrincipalsData>) => queryOptions<ListPrincipalsResponse, ListPrincipalsError, ListPrincipalsResponse, ReturnType<typeof listPrincipalsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listPrincipals({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listPrincipalsQueryKey(options)
});

/**
 * Creates a token-only identity (no web login).
 */
export const createIdentityMutation = (options?: Partial<Options<CreateIdentityData>>): UseMutationOptions<CreateIdentityResponse, CreateIdentityError, Options<CreateIdentityData>> => {
    const mutationOptions: UseMutationOptions<CreateIdentityResponse, CreateIdentityError, Options<CreateIdentityData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createIdentity({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPrincipalQueryKey = (options: Options<GetPrincipalData>) => createQueryKey('getPrincipal', options);

/**
 * A principal with its tokens and repository grants.
 */
export const getPrincipalOptions = (options: Options<GetPrincipalData>) => queryOptions<GetPrincipalResponse, GetPrincipalError, GetPrincipalResponse, ReturnType<typeof getPrincipalQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPrincipal({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPrincipalQueryKey(options)
});

/**
 * Enables/disables an identity or renames its display name.
 */
export const updatePrincipalMutation = (options?: Partial<Options<UpdatePrincipalData>>): UseMutationOptions<UpdatePrincipalResponse, UpdatePrincipalError, Options<UpdatePrincipalData>> => {
    const mutationOptions: UseMutationOptions<UpdatePrincipalResponse, UpdatePrincipalError, Options<UpdatePrincipalData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updatePrincipal({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listTokensQueryKey = (options: Options<ListTokensData>) => createQueryKey('listTokens', options);

/**
 * Tokens of a principal (secrets are never returned).
 */
export const listTokensOptions = (options: Options<ListTokensData>) => queryOptions<ListTokensResponse, ListTokensError, ListTokensResponse, ReturnType<typeof listTokensQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTokens({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTokensQueryKey(options)
});

/**
 * Issues a token. The secret is returned once. Admins may mint tokens for
 * identities and for their own GitHub principal only.
 */
export const createTokenMutation = (options?: Partial<Options<CreateTokenData>>): UseMutationOptions<CreateTokenResponse2, CreateTokenError, Options<CreateTokenData>> => {
    const mutationOptions: UseMutationOptions<CreateTokenResponse2, CreateTokenError, Options<CreateTokenData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createToken({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Revokes a token immediately.
 */
export const revokeTokenMutation = (options?: Partial<Options<RevokeTokenData>>): UseMutationOptions<RevokeTokenResponse, RevokeTokenError, Options<RevokeTokenData>> => {
    const mutationOptions: UseMutationOptions<RevokeTokenResponse, RevokeTokenError, Options<RevokeTokenData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await revokeToken({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listRepositoriesQueryKey = (options?: Options<ListRepositoriesData>) => createQueryKey('listRepositories', options);

/**
 * Repositories, alphabetically, with a substring filter.
 */
export const listRepositoriesOptions = (options?: Options<ListRepositoriesData>) => queryOptions<ListRepositoriesResponse, ListRepositoriesError, ListRepositoriesResponse, ReturnType<typeof listRepositoriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRepositories({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRepositoriesQueryKey(options)
});

export const listRepositoriesInfiniteQueryKey = (options?: Options<ListRepositoriesData>): QueryKey<Options<ListRepositoriesData>> => createQueryKey('listRepositories', options, true);

/**
 * Repositories, alphabetically, with a substring filter.
 */
export const listRepositoriesInfiniteOptions = (options?: Options<ListRepositoriesData>) => {
    const opts = infiniteQueryOptions<ListRepositoriesResponse, ListRepositoriesError, InfiniteData<ListRepositoriesResponse>, QueryKey<Options<ListRepositoriesData>>, number | Pick<QueryKey<Options<ListRepositoriesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListRepositoriesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listRepositories({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listRepositoriesInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Deletes a repository: tags, manifests, grants and uploads go; blobs are
 * reclaimed by the next garbage collection.
 */
export const deleteRepositoryMutation = (options?: Partial<Options<DeleteRepositoryData>>): UseMutationOptions<DeleteRepositoryResponse, DeleteRepositoryError, Options<DeleteRepositoryData>> => {
    const mutationOptions: UseMutationOptions<DeleteRepositoryResponse, DeleteRepositoryError, Options<DeleteRepositoryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteRepository({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRepositoryQueryKey = (options: Options<GetRepositoryData>) => createQueryKey('getRepository', options);

/**
 * A repository with its tags and manifests (including referrers).
 */
export const getRepositoryOptions = (options: Options<GetRepositoryData>) => queryOptions<GetRepositoryResponse, GetRepositoryError, GetRepositoryResponse, ReturnType<typeof getRepositoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRepository({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRepositoryQueryKey(options)
});

/**
 * Deletes a manifest and every tag pointing at it.
 */
export const deleteRepositoryManifestMutation = (options?: Partial<Options<DeleteRepositoryManifestData>>): UseMutationOptions<DeleteRepositoryManifestResponse, DeleteRepositoryManifestError, Options<DeleteRepositoryManifestData>> => {
    const mutationOptions: UseMutationOptions<DeleteRepositoryManifestResponse, DeleteRepositoryManifestError, Options<DeleteRepositoryManifestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteRepositoryManifest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listRepositoryPermissionsQueryKey = (options: Options<ListRepositoryPermissionsData>) => createQueryKey('listRepositoryPermissions', options);

/**
 * Who may access a repository.
 */
export const listRepositoryPermissionsOptions = (options: Options<ListRepositoryPermissionsData>) => queryOptions<ListRepositoryPermissionsResponse, ListRepositoryPermissionsError, ListRepositoryPermissionsResponse, ReturnType<typeof listRepositoryPermissionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRepositoryPermissions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRepositoryPermissionsQueryKey(options)
});

/**
 * Removes a principal's grant on a repository.
 */
export const revokePermissionMutation = (options?: Partial<Options<RevokePermissionData>>): UseMutationOptions<RevokePermissionResponse, RevokePermissionError, Options<RevokePermissionData>> => {
    const mutationOptions: UseMutationOptions<RevokePermissionResponse, RevokePermissionError, Options<RevokePermissionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await revokePermission({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Grants (or changes) a principal's level on a repository.
 */
export const grantPermissionMutation = (options?: Partial<Options<GrantPermissionData>>): UseMutationOptions<GrantPermissionResponse, GrantPermissionError, Options<GrantPermissionData>> => {
    const mutationOptions: UseMutationOptions<GrantPermissionResponse, GrantPermissionError, Options<GrantPermissionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await grantPermission({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Removes a tag (the manifest stays).
 */
export const deleteRepositoryTagMutation = (options?: Partial<Options<DeleteRepositoryTagData>>): UseMutationOptions<DeleteRepositoryTagResponse, DeleteRepositoryTagError, Options<DeleteRepositoryTagData>> => {
    const mutationOptions: UseMutationOptions<DeleteRepositoryTagResponse, DeleteRepositoryTagError, Options<DeleteRepositoryTagData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteRepositoryTag({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSystemQueryKey = (options?: Options<GetSystemData>) => createQueryKey('getSystem', options);

/**
 * Storage backend, database size and registry totals.
 */
export const getSystemOptions = (options?: Options<GetSystemData>) => queryOptions<GetSystemResponse, DefaultError, GetSystemResponse, ReturnType<typeof getSystemQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSystem({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSystemQueryKey(options)
});

export const listUploadsQueryKey = (options?: Options<ListUploadsData>) => createQueryKey('listUploads', options);

/**
 * Upload sessions in flight.
 */
export const listUploadsOptions = (options?: Options<ListUploadsData>) => queryOptions<ListUploadsResponse, DefaultError, ListUploadsResponse, ReturnType<typeof listUploadsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listUploads({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listUploadsQueryKey(options)
});
